#!/bin/sh
set -e

PROGNAME=$(basename $0)

die() {
    echo "$PROGNAME: ERROR: $*" | fold -s -w "${COLUMNS:-80}" >&2
    exit 1
}


usage() {
    if [ "$*" != "" ] ; then
        echo "ERROR: $*"
    fi
    
    cat << EOF
Usage: $PROGNAME [OPTION ...]
  ...program description...
Options:
  -h, --help          display this usage message and exit
EOF

    exit 1
}

echo_list() {
    echo "<td><pre>"
    y t_list $1 --format=plain
    echo "</pre></td>"
}

cat <<EOF
<html>
<head>
<title>WALL</title>
</head>
<body>
<table>
<tr>
    <th>TODO</th>
    <th>WIP</th>
    <th>DONE</th>
</tr>
EOF

echo_list '--due <=sunday'
echo_list '--started'
echo_list '--done thisweek'

cat <<EOF
</table>
</body>
</html>
EOF

# vim:set ts=4 sw=4 et:
